services:

  minio-admin-files:
    image: minio/minio:latest
    container_name: minio-admin-files
    restart: always
    command: server --console-address :9001 /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_UPLOAD_LIMIT=10GiB
    volumes:
      - ${MINIO_FOLDER_LOCATION}:/data
    ports:
      - 9002:9000
      - 9003:9001
    networks:
      - minio-admin-files-network
  
  api-minio-admin:
    build: .
    container_name: api-minio-admin
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_FOLDER_LOCATION: ${MINIO_FOLDER_LOCATION}
    ports:
        - "9999:9999"
    networks:
      - minio-admin-files
      
networks:
  minio-admin-files:
    external: true

